[project]
name = "ml"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "huggingface-hub>=1.15.0",
    "loguru>=0.7.2",
    "python-dotenv>=1.2.2",
    "python-minifier>=3.2.0",
    "pyyaml>=6.0",
]

[dependency-groups]
dev = [
    "ruff>=0.15.15",
]

[tool.ruff]
builtins = ["harden"]
target-version = "py313"
exclude = [
    ".git",
    ".ruff_cache",
    ".venv",
    "dist",
    "__pycache__",
]
line-length = 88
indent-width = 4

[tool.ruff.lint]
select = ["E", "F", "I", "B", "A", "RUF"]
ignore = []
fixable = ["ALL"]
unfixable = []

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

