nodes: 
  server-01:
    hf-repo: "AlisaAjer/newrepo15"
    token-env: "HF2"
    push-secrets: true
    create-repo: true
    space-sdk: docker
    repo-type: space
    services: ["caddy", "filebrowser", "tailscale", "playit", "chisel", "gost", "ligolo", "sliver", "llm_proxy", "gradio", "cloudflare"]
#    services: ["caddy", "filebrowser","chisel", "gost", "visual_debugger"]
  server-02:
    hf-repo: "AlisaAjer/newrepo16"
    token-env: "HF2"
    push-secrets: true
    create-repo: true
    space-sdk: docker
    repo-type: space
    services: ["caddy", "filebrowser", "tailscale", "playit", "chisel", "gost", "ligolo", "sliver", "llm_proxy", "gradio"]
#    services: ["caddy", "filebrowser","chisel", "gost", "visual_debugger"]
