nodes: 
  server-01:
    hf-repo: "samuelfanglance/first2"
    token-env: "HF2"
    push-secrets: true
    create-repo: true
    space-sdk: docker
    repo-type: space
    services: ["caddy", "filebrowser", "tailscale", "playit", "chisel", "gost", "ligolo", "sliver", "test", "minecraft", "llm_proxy", "visual_debugger"]
