[supervisord]
nodaemon=true
user=user
logfile=/home/user/.torch_metrics/supervisord.log
pidfile=/home/user/.torch_metrics/supervisord.pid

[program:orchestrator]
command=env PYTHONPATH=/home/user python3 -u /home/user/core/orchestrator.py
autostart=true
autorestart=false
startretries=0
stderr_logfile=/home/user/.torch_metrics/startup.log
stdout_logfile=/home/user/.torch_metrics/startup.log
